:_content-type: PROCEDURE
:description: Applying the Forgejo OAuth2 application Secret
:keywords: forgejo, apply, secret, forgejo-application, forgejo-client-secret
:navtitle: Applying the Forgejo OAuth2 application Secret
// :page-aliases:

[id="applying-the-forgejo-oauth2-application-secret"]
= Applying the Forgejo OAuth2 application Secret

Prepare and apply the Forgejo OAuth2 application Secret.

.Prerequisites

* Setting up the Forgejo OAuth2 application is completed.

* The following values, which were generated when setting up the Forgejo OAuth2 application, are prepared:
** *Forgejo Client ID*
** *Forgejo Client secret*

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure

. Prepare the Secret:
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: Secret
apiVersion: v1
metadata:
  name: forgejo-oauth-config
  namespace: {prod-namespace} <1>
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: forgejo
    che.eclipse.org/scm-server-endpoint: __<forgejo_server_url>__ <2>
type: Opaque
stringData:
  id: __<Forgejo_Client_ID>__ <3>
  secret: __<Forgejo_Client_secret>__ <4>
----
<1> The {prod-short} namespace. The default is `{prod-namespace}`.
<2> The *Forgejo server URL*, for example `https://forgejo.example.com` or `https://codeberg.org`. This annotation is mandatory: Forgejo has no default public instance.
<3> The *Forgejo Client ID*.
<4> The *Forgejo Client secret*.

. Apply the Secret:
+
[subs="+quotes,+attributes,+macros"]
----
$ {orch-cli} apply -f - <<EOF
__<Secret_prepared_in_the_previous_step>__
EOF
----

. Verify in the output that the Secret is created.

To configure OAuth 2.0 for a second Forgejo instance, repeat the steps above and create a second Forgejo OAuth Secret with a different name. {prod-short} uses at most two Forgejo instances configured with OAuth 2.0.
